#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use File::Spec;
use lib File::Spec->catfile( $FindBin::Bin, qw/.. lib/ );

use FCGI::Server::Lighttpd;

my $flight = FCGI::Server::Lighttpd->new_with_options;
$flight->run(@ARGV);

